export const SEARCH_FOCUS = 'search_focus'
export const SEARCH_BLUR = 'search_blur'
export const SET_LIST = 'set_list'
export const MOUSE_ENTER = 'mouse_enter'
export const MOUSE_LEAVE = 'mouse_leave'
export const CHANGE_PAGE = 'change_page'